[tools]
node = "24.13.0"
pnpm = "10.28.2"
ruby = "3.4.6"
gradle = "8.5.0"
java = "corretto-17.0.16.8.1"
python = "3.14.2"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[env]
